<?xml version="1.0" standalone="no"?><!DOCTYPE        Heroe [         <!ELEMENT Heroe (Superheroes)*>         <!ELEMENT Superheroes (Superheroe)*>         <!ELEMENT Superheroe (Nombre|IdentidadS|Batallas|Habilidades)*>         <!ATTLIST Superheroe                        genero CDATA #REQUIRED                        id CDATA #REQUIRED                        procedencia CDATA "Terrestre">        <!ELEMENT Nombre (#PCDATA)>        <!ELEMENT IdentidadS (#PCDATA)>        <!ELEMENT Batallas (Batalla)*>        <!ELEMENT Batalla (Lugar|Fecha_comienzo|Fecha_fin)*>        <!ELEMENT Lugar (#PCDATA)>        <!ELEMENT Fecha_comienzo (#PCDATA)>        <!ELEMENT Fecha_fin (#PCDATA)>        <!ELEMENT Habilidades (Habilidad)*>        <!ELEMENT Habilidad (Tipo|Definicion)*>        <!ELEMENT Tipo (#PCDATA)><!ELEMENT Definicion (#PCDATA)>        ]><Heroe>	<Superheroes>		<Superheroe procedencia="Terrestre" genero="hombre" id="1">			<Nombre>Stephen Vincent</Nombre>			<IdentidadS>Dr. Strange</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Socovia</Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion>Puede crear ilusiones y proyecciones astrales</Definicion>				</Habilidad>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion>Comunicaci√≥n a traves de la mente</Definicion>				</Habilidad>			</Habilidades>		</Superheroe>		<Superheroe procedencia="extraterrestre" genero="hombre" id="2">			<Nombre>Thor</Nombre>			<IdentidadS>Thor</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Nueva York</Lugar>					<Fecha_comienzo>2017</Fecha_comienzo>					<Fecha_fin>2017</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Asgard</Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Wakanda</Lugar>					<Fecha_comienzo>2018</Fecha_comienzo>					<Fecha_fin>2018</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion>Superfuerza que loconvierte en el mas fuerte de asgard y universo </Definicion>				</Habilidad>				<Habilidad>					<Tipo>SObrenatural</Tipo>					<Definicion>Dios del trueno </Definicion>				</Habilidad>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion> Capacidad de poder volar a gran velocidad</Definicion>				</Habilidad>			</Habilidades>		</Superheroe>		<Superheroe procedencia="Terrestre" genero="hombre" id="3">			<Nombre>T'Challa</Nombre>			<IdentidadS>Black Panther</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Aeropuerto </Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Wakanda</Lugar>					<Fecha_comienzo>2018</Fecha_comienzo>					<Fecha_fin>2018</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion></Definicion>				</Habilidad>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion></Definicion>				</Habilidad>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion>Traje hecho de vibranium que le proporciona mas resistencia y unos guantes que generan dagas de energia</Definicion>				</Habilidad>			</Habilidades>		</Superheroe><Superheroe procedencia="Terrestre" genero="hombre " id="4"><Nombre>Bruce </Nombre><IdentidadS>Hulk</IdentidadS><Batallas><Batalla><Fecha_comienzo>2017</Fecha_comienzo><Fecha_fin>2017</Fecha_fin><Lugar>Asgard</Lugar></Batalla><Batalla><Fecha_comienzo>2015</Fecha_comienzo><Fecha_fin>2015</Fecha_fin><Lugar>Sokovia</Lugar></Batalla><Batalla><Fecha_comienzo>2013</Fecha_comienzo><Fecha_fin>2103</Fecha_fin><Lugar>New York </Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>Sobrenatural</Tipo><Definicion>Superfuerza </Definicion></Habilidad><Habilidad><Tipo>Sobrenatural</Tipo><Definicion>Super saltos</Definicion></Habilidad><Habilidad><Tipo>sobrenatural</Tipo><Definicion>Golpes</Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="Extraterrestre" genero="hombre" id="5"><Nombre>Thanos </Nombre><IdentidadS>Thanos </IdentidadS><Batallas><Batalla><Fecha_comienzo>2019</Fecha_comienzo><Fecha_fin>2019 </Fecha_fin><Lugar>La tierra</Lugar></Batalla><Batalla><Fecha_comienzo>2020 </Fecha_comienzo><Fecha_fin>2020</Fecha_fin><Lugar>Universo </Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>fuerza</Tipo><Definicion>superfuerza &gt; thor y hulk </Definicion></Habilidad><Habilidad><Tipo>teletransporte</Tipo><Definicion>capaz de teletransportarse cin las gemas </Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="extraterrestre" genero="hombre" id="6"><Nombre>Thanos </Nombre><IdentidadS>Thanos </IdentidadS><Batallas><Batalla><Fecha_comienzo>2019</Fecha_comienzo><Fecha_fin>2019</Fecha_fin><Lugar>universo </Lugar></Batalla><Batalla><Fecha_comienzo>2020</Fecha_comienzo><Fecha_fin>2020</Fecha_fin><Lugar>la tierra</Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>sobrenatural</Tipo><Definicion>mucha fuerza &gt; thor y hulk</Definicion></Habilidad><Habilidad><Tipo>sobrenatural</Tipo><Definicion>super inteligencia </Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="terrestre" genero="hombre" id="7"><Nombre>miguel</Nombre><IdentidadS>salas</IdentidadS><Batallas><Batalla><Fecha_comienzo>2018</Fecha_comienzo><Fecha_fin>2018</Fecha_fin><Lugar>ufv</Lugar></Batalla><Batalla><Fecha_comienzo>2020</Fecha_comienzo><Fecha_fin>2020</Fecha_fin><Lugar>ufv</Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>natural</Tipo><Definicion>estudiar</Definicion></Habilidad><Habilidad><Tipo>natural </Tipo><Definicion>aprobar </Definicion></Habilidad><Habilidad><Tipo>natural </Tipo><Definicion>suspender </Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="terrestre" genero="hombre " id="8"><Nombre>liam </Nombre><IdentidadS>liam </IdentidadS><Batallas><Batalla><Fecha_comienzo>2020</Fecha_comienzo><Fecha_fin>2020</Fecha_fin><Lugar>ufv</Lugar></Batalla><Batalla><Fecha_comienzo>2021</Fecha_comienzo><Fecha_fin>2021</Fecha_fin><Lugar>ufv</Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>natural</Tipo><Definicion>aprobar</Definicion></Habilidad><Habilidad><Tipo>natural </Tipo><Definicion>estudiar </Definicion></Habilidad><Habilidad><Tipo>natural</Tipo><Definicion>suspender </Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="Terrestre" id="9" genero="hombre "><Nombre>Bruce wayne </Nombre><IdentidadS>batman </IdentidadS><Batallas><Batalla><Fecha_comienzo>2010</Fecha_comienzo><Fecha_fin>2012</Fecha_fin><Lugar>Gotham </Lugar></Batalla><Batalla><Fecha_comienzo>2019</Fecha_comienzo><Fecha_fin>2019</Fecha_fin><Lugar>eeuu </Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>natural</Tipo><Definicion>es muy rico </Definicion></Habilidad></Habilidades></Superheroe></Superheroes></Heroe>