<?xml version="1.0" standalone="no"?><!DOCTYPE        Heroe [         <!ELEMENT Heroe (Superheroes)*>         <!ELEMENT Superheroes (Superheroe)*>         <!ELEMENT Superheroe (Nombre|IdentidadS|Batallas|Habilidades)*>         <!ATTLIST Superheroe                        genero CDATA #REQUIRED                        id CDATA #REQUIRED                        procedencia CDATA "Terrestre">        <!ELEMENT Nombre (#PCDATA)>        <!ELEMENT IdentidadS (#PCDATA)>        <!ELEMENT Batallas (Batalla)*>        <!ELEMENT Batalla (Lugar|Fecha_comienzo|Fecha_fin)*>        <!ELEMENT Lugar (#PCDATA)>        <!ELEMENT Fecha_comienzo (#PCDATA)>        <!ELEMENT Fecha_fin (#PCDATA)>        <!ELEMENT Habilidades (Habilidad)*>        <!ELEMENT Habilidad (Tipo|Definicion)*>        <!ELEMENT Tipo (#PCDATA)><!ELEMENT Definicion (#PCDATA)>        ]><Heroe>	<Superheroes>		<Superheroe procedencia="Terrestre" genero="hombre" id="1">			<Nombre>Stephen Vincent</Nombre>			<IdentidadS>Dr. Strange</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Socovia</Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion>Puede crear ilusiones y proyecciones astrales</Definicion>				</Habilidad>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion>Comunicaci√≥n a traves de la mente</Definicion>				</Habilidad>			</Habilidades>		</Superheroe>		<Superheroe procedencia="extraterrestre" genero="hombre" id="2">			<Nombre>Thor</Nombre>			<IdentidadS>Thor</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Nueva York</Lugar>					<Fecha_comienzo>2017</Fecha_comienzo>					<Fecha_fin>2017</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Asgard</Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Wakanda</Lugar>					<Fecha_comienzo>2018</Fecha_comienzo>					<Fecha_fin>2018</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion>Superfuerza que loconvierte en el mas fuerte de asgard y universo </Definicion>				</Habilidad>				<Habilidad>					<Tipo>SObrenatural</Tipo>					<Definicion>Dios del trueno </Definicion>				</Habilidad>				<Habilidad>					<Tipo>Sobrenatural</Tipo>					<Definicion> Capacidad de poder volar a gran velocidad</Definicion>				</Habilidad>			</Habilidades>		</Superheroe>		<Superheroe procedencia="Terrestre" genero="hombre" id="3">			<Nombre>T'Challa</Nombre>			<IdentidadS>Black Panther</IdentidadS>			<Batallas>				<Batalla>					<Lugar>Aeropuerto </Lugar>					<Fecha_comienzo>2019</Fecha_comienzo>					<Fecha_fin>2019</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>Wakanda</Lugar>					<Fecha_comienzo>2018</Fecha_comienzo>					<Fecha_fin>2018</Fecha_fin>				</Batalla>				<Batalla>					<Lugar>La Tierra</Lugar>					<Fecha_comienzo>2020</Fecha_comienzo>					<Fecha_fin>2020</Fecha_fin>				</Batalla>			</Batallas>			<Habilidades>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion></Definicion>				</Habilidad>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion></Definicion>				</Habilidad>				<Habilidad>					<Tipo>Natural</Tipo>					<Definicion>Traje hecho de vibranium que le proporciona mas resistencia y unos guantes que generan dagas de energia</Definicion>				</Habilidad>			</Habilidades>		</Superheroe><Superheroe procedencia="Terrestre" genero="hombre " id="4"><Nombre>Bruce </Nombre><IdentidadS>Hulk</IdentidadS><Batallas><Batalla><Fecha_comienzo>2017</Fecha_comienzo><Fecha_fin>2017</Fecha_fin><Lugar>Asgard</Lugar></Batalla><Batalla><Fecha_comienzo>2015</Fecha_comienzo><Fecha_fin>2015</Fecha_fin><Lugar>Sokovia</Lugar></Batalla><Batalla><Fecha_comienzo>2013</Fecha_comienzo><Fecha_fin>2103</Fecha_fin><Lugar>New York </Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>Sobrenatural</Tipo><Definicion>Superfuerza </Definicion></Habilidad><Habilidad><Tipo>Sobrenatural</Tipo><Definicion>Super saltos</Definicion></Habilidad><Habilidad><Tipo>sobrenatural</Tipo><Definicion>Golpes</Definicion></Habilidad></Habilidades></Superheroe><Superheroe procedencia="Terrestre" id="5" genero="femenino"><Nombre>Ana</Nombre><IdentidadS>Catwoman </IdentidadS><Batallas><Batalla><Fecha_comienzo>2018</Fecha_comienzo><Fecha_fin>2018</Fecha_fin><Lugar>el patio de su casa</Lugar></Batalla><Batalla><Fecha_comienzo>2000</Fecha_comienzo><Fecha_fin>2000</Fecha_fin><Lugar>boston</Lugar></Batalla></Batallas><Habilidades><Habilidad><Tipo>natural</Tipo><Definicion>mucha agilidad y garras de gato</Definicion></Habilidad></Habilidades></Superheroe></Superheroes></Heroe>